name = "fsmaker"
description = "Command line tool to create embedded filesystem images"
version = "0.1.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["fsmaker"]

[[depends-on]]
ada_toml = "*"
littlefs = "*"
ansiada = "*"
simple_logging = "*"
aaa = "*"
clic = "*"

[[pins]]
clic = { url='https://github.com/alire-project/clic.git' }

[configuration.values]
littlefs.No_Malloc = true
