name = "fsmaker"
description = "Shiny new project"
version = "0.0.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["fsmaker"]

[[depends-on]]
gnat_native = "^10.3.0-1"
ada_toml = "*"
littlefs = "*"
ansiada = "*"
simple_logging = "*"
aaa = "*"
clic = "*"

[[pins]]
clic = { url='https://github.com/alire-project/clic.git' }
